export type ColorsType = {
  lightPurple_1: string;
  lightPurple_2: string;
  lightPurple_3: string;
  lightPurple_4: string;
  darkBlue_1: string;
  darkBlue_2: string;
  darkBlue_3: string;
  darkBlue_4: string;
  darkBlue_5: string;
  lightGray: string;
  grayText: string;
  grayText1: string;
  grayText2: string;
  grayText3: string;
  white: string;
  whiteLight: string;
  textBlack: string;
  textGreenLight: string;
  lightRed: string;
  mainRed: string;
  lightPink: string;
};
