import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ChangeEvent, useState } from "react";
import { getWheather } from "../services/wheather";
import { ReactMap } from "../shared/components/Map";
import { WheatherType } from "../interface/data";
import { Button } from "../shared/components/Button";

const Home: NextPage = () => {
  const [data, setData] = useState<WheatherType>();
  const [text, setText] = useState<string>();
  const [loading, setLoading] = useState<boolean>(false);

  console.log("data", data);

  const handleSearch = async () => {
    setLoading(true);
    try {
      const res = await getWheather({ q: text });

      console.log(res);
      setData(res.data);
    } catch (err) {
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setText(e.target.value);
  };

  if (loading) return <h1>Loading ....</h1>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input placeholder="Search..." onChange={handleChange} />
        <button onClick={handleSearch}>Search</button>
        <Button size="lg" color="primary">
          Search
        </Button>
      </main>

      <div>
        <h1>{data?.name}</h1>
        <h1>{data?.main.feels_like}</h1>
        <h4>{data?.name}</h4>
        {/* <ReactMap lat={data?.coord.lat ?? 0} lon={data?.coord.lon ?? 0} /> */}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
