import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { getMovies } from "../services/movie";

export default function Home({ movies, hasError }) {
  // const [data, setData] = useState();
  // const a = useQuery("tofos",getTodos,{
  //   onSucces:()=>{

  //   }
  // })

  // useEffect(() => {
  //   getMovies().then((res) => {
  //     console.log(res);
  //     setData(res.data.Search);
  //   });
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>NextJS APP</h1>
        <ul>
          {movies?.map((item, index) => (
            <li key={index}>{item.Title}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const res = await getMovies();

    return {
      props: {
        movies: res.data.Search,
      },
    };
  } catch (err) {
    return {
      redirect: "/404",
      // props: {
      //   hasError: true,
      // },
    };
  }
}
